/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function detectFormat(data: Buffer, sourceName?: string | undefined | null): string

export declare function parseBytes(data: Buffer, options?: ParseOptions | undefined | null): any

export declare function extractMedia(data: Buffer, resource: string, options?: ParseOptions | undefined | null): Buffer

export interface ParseOptions {
  sourceName?: string
  contentType?: string
  format?: string
  maxParseBytes?: number
  sheet?: string
  rows?: Array<number>
  columns?: Array<string>
  limit?: number
  offset?: number
  pages?: Array<number>
  maxWorkUnits?: number
}
