/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function detectFormat(data: Buffer, sourceName?: string | undefined | null): string

export declare function parseBytes(data: Buffer, options?: ParseOptions | undefined | null): any

export interface ParseOptions {
  sourceName?: string
  contentType?: string
  format?: string
  maxParseBytes?: number
}
